services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"      # HTTP port
      - "443:443"    # HTTPS port
    restart: always

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5050:8000"    # 改為5000避免與其他服務衝突
    environment:
      DATABASE_URL: "mariadb://db_user:db_password@db:3306/b2b_doc"
      SMTP_SERVER: "smtp"
      SMTP_PORT: "1025"
      SMTP_USER: ""
      SMTP_PASSWORD: ""
    depends_on:
      - db
      - smtp
    volumes:
      # Mount into the package directory so the container's /app entrypoint isn't overwritten
      - ./backend/app:/app

  smtp:
    image: "mailhog/mailhog"
    restart: always
    ports:
      - "1025:1025" # SMTP
      - "8025:8025" # Web UI

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:8080"    # 改回8080，避免與前端80端口衝突
    environment:
      PMA_HOST: db
      PMA_USER: root
      PMA_PASSWORD: "00000000"
    depends_on:
      - db
  db:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "00000000"
      MYSQL_DATABASE: b2b_doc
      MYSQL_USER: 
      MYSQL_PASSWORD: "00000000"
    ports:
      - "3307:3306"  # 改為3307避免與本機MySQL衝突
    volumes:
      - db_data:/var/lib/mysql
      - "./db/init.sql:/docker-entrypoint-initdb.d/init.sql"

volumes:
  db_data: